global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_cache:6379']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']